Position centre
WildCodeSchool/toulouse-0219-java-culture pull request #17
Opened 2019-04-25 15:37 UTC by liliajerbi

2019-04-25 16:00 UTC, Jeremy-Ganderatz requested changes
ya deux trois saut de lignes pour lesquels c'est sur Bastien va pas valider.

2019-04-25 16:01 UTC, Jeremy-Ganderatz requested changes
pareil ya des sauts de lignes et aussi tu as laisser des commentaires.

2019-04-26 08:36 UTC, Jeremy-Ganderatz approved these changes

2019-04-26 08:56 UTC, bastienapp requested changes

2019-04-26 08:56 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/culture/ListMuseum.java
> +                if(i == 0) {
CTRL + MAJ + ALT + L

2019-04-26 08:56 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/culture/MapsActivity.java
> +                ActivityCompat.requestPermissions(MapsActivity.this, new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, REQUEST_LOCATION);
CTRL + MAJ + ALT + L

2019-04-26 08:56 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/culture/MapsActivity.java
> +                if(i == 0) {
CTRL + MAJ + ALT + L

2019-04-26 09:21 UTC, Jeremy-Ganderatz requested changes
il reste des commentaires.

2019-04-26 09:27 UTC, bastienapp approved these changes

2019-04-26 09:50 UTC, Jeremy-Ganderatz approved these changes

2019-04-26 09:50 UTC, merged